<?php
/**
 * Template Overrides for WooCommerce pages
 *
 * @package Fancy Lab
 */

/** Modifying WooCommerce templates using actions and filters hooks
 * 1. Add container and row wrappers
 * 2. Add closing tags of container and row wrappers
 * 3. Remove default sidebar to be echoed later inside new sidebar tags
 * 4. Adding sidebar again after removing default sidebar that's generated by woocommerce. We remove it because it's in the wrong place!
 * 4.A. Add sidebar tags
 * 4.B. Add sidebar again using another hook (custom)
 * 4.C. Add closing sidebar tags
 * 5. If we in Shop page, add a short description to the product
 * 6. Add opening shop tags
 * 7. Add closing shop tags
 */

function fancy_lab_wc_modify() {
  // 1. Add opening container and row wrappers tags
  function fancy_lab_open_container_row() {
    echo '<div class="container shop-content"><div class="row">';
  }

  add_action( 'woocommerce_before_main_content', 'fancy_lab_open_container_row', 5 ); // must have priority greater than 10, the default priority is 10

  // 2. Add closing container and row wrappers tags
  function fancy_lab_close_container_row() {
    echo '</div></div>';
  }

  add_action( 'woocommerce_after_main_content', 'fancy_lab_close_container_row', 5 ); // should have the same priority as <opening tags>

  // 3. Remove default sidebar to be echoed later inside new sidebar tags
  remove_action( 'woocommerce_sidebar', 'woocommerce_get_sidebar' );

  // Add sidebar only to shop page and remove it from other pages
  if ( is_shop() ) {
    // 4. Adding sidebar again after removing default sidebar that's generated by woocommerce. We remove it because it's in the wrong place!
    // 4.A. Add sidebar opening tags
    function fancy_lab_open_sidebar_tags() {
      echo '<div class="sidebar-shop col-lg-3 col-md-4 order-2 order-md-1">';
    }

    add_action( 'woocommerce_before_main_content', 'fancy_lab_open_sidebar_tags', 6 ); // (6) because we want it inside .container and row wrappers, which have a value of (5)

    // 4.B. Add sidebar again using another hook (custom)
    add_action( 'woocommerce_before_main_content', 'woocommerce_get_sidebar', 7 ); // (6: tags, 7: get_sidebar)

    // 4.C. Add closing sidebar tags
    function fancy_lab_close_sidebar_tags() {
      echo '</div>';
    }

    add_action( 'woocommerce_before_main_content', 'fancy_lab_close_sidebar_tags', 8 );

    // 5. If we in Shop page, add a short description to the product
    add_action( 'woocommerce_after_shop_loop_item_title', 'the_excerpt', 1 );
  }

  // 6. Add opening shop tags
  function fancy_lab_open_shop_tags() {
    // The content size for shop page is 9 col, for other pages is 12
    if ( is_shop() ) {
      echo '<div class="col-lg-9 col-md-8 order-1 order-md-2">';
    } else {
      echo '<div class="col">';
    }
  }

  add_action( 'woocommerce_before_main_content', 'fancy_lab_open_shop_tags', 9 );

  // 7. Add closing shop tags
  function fancy_lab_close_shop_tags(){
    echo '</div>';
  }

  add_action( 'woocommerce_after_main_content', 'fancy_lab_close_shop_tags', 4 );

  // (TEST): Testing filters hooks to make changes
  // Filters return only true or false
  // Filter: input -> processing -> output
  /*
  function fancy_lab_remove_shop_title( $val ) { // input
    $val = false; // processing (You can't return a string, just bool)
    return $val; // output
    // If one $param, you can write the function in a simpler way function x() { return false }
  }

  add_filter( 'woocommerce_show_page_title', 'fancy_lab_remove_shop_title' );
  */

}

add_action( 'wp', 'fancy_lab_wc_modify' );